---
title: "002_geneticArchitectures"
author: "Sarah P. Flanagan"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: default
  pdf_document:
    dev: png
---

In this document I'm generating files for a poster. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,out.extra='',fig.pos="H",dpi=300,fig.path="../figs/")
knitr::opts_knit$set(root.dir='../results/')
```

```{r, echo=FALSE}
library(knitr)
library(RColorBrewer)
library(scales)
source("../R/002_freq_functions.R")
read_chunk("../R/002_expectationTests.R")
cols<-c(courter="#33a02c",parent="#1f78b4",cpref="#b2df8a",ppref="#a6cee3")
cols2<-c(CP='#a1dab4',NCP='#41b6c4',CNP='#2c7fb8',NCNP='#253494')
```

Get the data (we won't plot this right now)
```{r read_data,eval=FALSE}
u<-plot.pc.reps("^parent-courter-nogenetics_[1-5]_summary.txt",cols, make.plot = FALSE)
l<-plot.pc.reps("^parent-courter_[1-5]_summary.txt",cols,make.plot=FALSE)
s<-plot.pc.reps("^parent-courter_supergene_[1-5]_summary.txt",cols,make.plot=FALSE)
saveRDS(u,"pc-unlinked.RDS")
saveRDS(l,"pc-linked.RDS")
saveRDS(s,"pc-supergenes.RDS")
```
```{r read_RDS,eval=TRUE}
u<-readRDS("pc-unlinked.RDS")
l<-readRDS("pc-linked.RDS")
s<-readRDS("pc-supergenes.RDS")
```

## Unlinked additive genetic variation

```{r courtParent_unlinked, echo=FALSE,out.extra='',fig.pos="H",fig.cap="Morph freqs with unlinked SNPs"}
png("../figs/parentCourterU_morphs.png",height=8,width=18,units="in",res=300)
plot.morphs.reps(u,cols2,ncols = 4)
dev.off()
```

I'm going to take a small subset of these to demonstrate the patterns

```{r parentCourterU_sub, echo=FALSE,out.extra='',fig.pos="H",fig.cap="parentCourterU_sub",fig.width=6,fig.height=10}
png("../figs/parentCourterU_sub.png",height=8,width=18,units="in",res=300)
plot.morphs.reps(u[c(1,5,9)],cols2,ncols = 3,cex=2.5,lwd=4)
dev.off()
```

## Linked additive genetic variation

```{r courtParent_linked, echo=FALSE,out.extra='',fig.pos="H",fig.cap="Morph freqs with linked SNPs"}
png("../figs/parentCourterL.png",height=8,width=24,units="in",res=300)
plot.morphs.reps(l,cols2,ncols = 4)
dev.off()
```

```{r parentCourterL_sub}
png("../figs/parentCourterL_sub.png",height=8,width=24,units="in",res=300)
plot.morphs.reps(l[c(1,9,3,5)],cols2,ncols = 4,cex=2.5,lwd=4)
dev.off()
```
## Supergenes

```{r courtParent_supergenes, echo=FALSE,out.extra='',fig.pos="H",fig.cap="Morph freqs with supergenes",fig.height=10,fig.width=10}
png("../figs/parentCourterS.png",height=8,width=28,units="in",res=300)
plot.morphs.reps(s,cols2,ncols = 4)
dev.off()
```
```{r parentCourterS_sub}
png("../figs/parentCourterS_sub.png",height=8,width=28,units="in",res=300)
plot.morphs.reps(s[c(1,5,7,9,10)],cols2,ncols = 5,cex=2.5,lwd=4)
dev.off()
```